const LANG_STORAGE_KEY = 'nategraLang';

// Hero images are listed in assets/hero/manifest.js (HERO_MANIFEST), generated by
// scripts/load_hero_images.py.
//
// Reference images + captions live in assets/references/manifest.js
// (REFERENCES_MANIFEST), generated by scripts/load_reference_images.py.
// Captions are stored per-language inside the manifest and applied via applyLang().

function detectLang() {
    const stored = localStorage.getItem(LANG_STORAGE_KEY);
    if (stored && SUPPORTED_LANGS.includes(stored)) return stored;

    const browser = (navigator.language || '').slice(0, 2).toLowerCase();
    if (SUPPORTED_LANGS.includes(browser)) return browser;

    return DEFAULT_LANG;
}

function setLang(lang) {
    applyLang(lang);
    localStorage.setItem(LANG_STORAGE_KEY, lang);
    document.querySelectorAll('.lang-switcher button').forEach((btn) => {
        btn.setAttribute('aria-pressed', btn.dataset.lang === lang ? 'true' : 'false');
    });
}

function loadImage(src) {
    return new Promise((resolve, reject) => {
        const i = new Image();
        i.crossOrigin = 'anonymous';
        i.onload = () => resolve(i);
        i.onerror = reject;
        i.src = src;
    });
}

async function burnLogo(heroSrc, logoSrc) {
    const [hero, logo] = await Promise.all([loadImage(heroSrc), loadImage(logoSrc)]);

    const canvas = document.createElement('canvas');
    canvas.width = hero.naturalWidth;
    canvas.height = hero.naturalHeight;
    const ctx = canvas.getContext('2d');

    ctx.drawImage(hero, 0, 0);

    // Logo width: 8% of image width, positioned 3% from each edge.
    const margin = Math.round(hero.naturalWidth * 0.03);
    const logoW = Math.round(hero.naturalWidth * 0.08);
    const logoH = Math.round(logo.naturalHeight * (logoW / logo.naturalWidth));

    // Render the logo as a white silhouette on an offscreen canvas so the
    // burnt mark reads consistently over any photo region (matches the
    // mobile HTML overlay). source-in keeps only pixels that overlap the
    // existing alpha, recolouring them while preserving the shape.
    const whiteLogo = document.createElement('canvas');
    whiteLogo.width = logoW;
    whiteLogo.height = logoH;
    const whiteCtx = whiteLogo.getContext('2d');
    whiteCtx.drawImage(logo, 0, 0, logoW, logoH);
    whiteCtx.globalCompositeOperation = 'source-in';
    whiteCtx.fillStyle = '#fff';
    whiteCtx.fillRect(0, 0, logoW, logoH);

    ctx.drawImage(whiteLogo, margin, margin + Math.round(logoH / 2));

    return new Promise((resolve, reject) => canvas.toBlob(
        (blob) => blob ? resolve(URL.createObjectURL(blob)) : reject(),
        'image/webp', 0.92
    ));
}

async function pickHeroImage() {
    const img = document.querySelector('#hero .hero-image');
    if (!img) return;

    const list = Array.isArray(HERO_MANIFEST) ? HERO_MANIFEST : [];
    if (!list.length) return;

    const file = list[Math.floor(Math.random() * list.length)];
    img.addEventListener('load', () => img.classList.add('is-loaded'), { once: true });
    img.addEventListener('error', () => img.remove(), { once: true });

    try {
        img.src = await burnLogo(`assets/hero/${file}`, 'assets/logo/Nategra_Logo-Bateleur.png');
    } catch {
        img.src = `assets/hero/${file}`;
    }
}

const AUTOPLAY_DWELL_MS = 5000;
const AUTOPLAY_ANIM_MS = 800;

function setCaptionContent(el, text) {
    const match = text.match(/^(.*?)(\s*\([^)]*\))$/);
    if (match) {
        const span = document.createElement('span');
        span.className = 'caption-source';
        span.textContent = match[2];
        el.replaceChildren(document.createTextNode(match[1]), span);
    } else {
        el.textContent = text;
    }
}

function buildReferenceFigure(item) {
    const figure = document.createElement('figure');
    figure.className = 'reference-item';

    const img = document.createElement('img');
    img.src = `assets/references/${item.src}`;
    img.alt = '';
    img.loading = 'lazy';
    img.draggable = false;
    img.addEventListener('error', () => figure.remove(), { once: true });

    const caption = document.createElement('figcaption');
    caption._captions = item.captions || {};
    const lang = document.documentElement.lang || DEFAULT_LANG;
    setCaptionContent(caption, caption._captions[lang] || caption._captions[DEFAULT_LANG] || '');

    figure.append(img, caption);
    return figure;
}

async function renderReferences() {
    const track = document.querySelector('.references-track');
    if (!track) return;

    const manifestItems = REFERENCES_MANIFEST && Array.isArray(REFERENCES_MANIFEST.items)
        ? [...REFERENCES_MANIFEST.items]
        : [];
    if (!manifestItems.length) return;

    for (let i = manifestItems.length - 1; i > 0; i--) {
        const j = Math.floor(Math.random() * (i + 1));
        [manifestItems[i], manifestItems[j]] = [manifestItems[j], manifestItems[i]];
    }

    // Seed two full passes so both sides of the initial view are populated.
    const fragment = document.createDocumentFragment();
    manifestItems.forEach((item) => fragment.append(buildReferenceFigure(item)));
    manifestItems.forEach((item) => fragment.append(buildReferenceFigure(item)));
    track.replaceChildren(fragment);

    setupCarousel(track, manifestItems);
}

function setupCarousel(track, manifestItems) {
    // Live-growing array — new items are appended as the carousel advances.
    let items = [...track.querySelectorAll('.reference-item')];
    if (!items.length) return;

    const n = manifestItems.length;
    const BUFFER = n + 1; // items to keep ahead of and behind the active item

    // appendCursor advances forward through the manifest (right side).
    let appendCursor = (2 * n) % n; // = 0; continues after the two seeded passes
    // prependCursor advances backward through the manifest (left side).
    let prependCursor = n - 1; // first prepend gives manifest[n-1], then n-2, …

    const findClosest = () => {
        const trackRect = track.getBoundingClientRect();
        const trackMid = trackRect.left + trackRect.width / 2;
        let closestIdx = 0, minDist = Infinity;
        items.forEach((item, idx) => {
            const r = item.getBoundingClientRect();
            const dist = Math.abs(r.left + r.width / 2 - trackMid);
            if (dist < minDist) { minDist = dist; closestIdx = idx; }
        });
        return closestIdx;
    };

    const updateActive = () => {
        const closestIdx = findClosest();
        items.forEach((item, idx) => {
            const diff = Math.abs(idx - closestIdx);
            item.classList.toggle('is-active', diff === 0);
            item.classList.toggle('is-near', diff === 1);
        });
    };

    const snapToNearest = () => {
        const idx = findClosest();
        const item = items[idx];
        const trackRect = track.getBoundingClientRect();
        const itemRect = item.getBoundingClientRect();
        track.scrollLeft += (itemRect.left + itemRect.width / 2) - (trackRect.left + trackRect.width / 2);
    };

    const appendNext = () => {
        const figure = buildReferenceFigure(manifestItems[appendCursor]);
        appendCursor = (appendCursor + 1) % n;
        track.append(figure);
        items.push(figure);
    };

    const prependNext = () => {
        const figure = buildReferenceFigure(manifestItems[prependCursor]);
        prependCursor = (prependCursor - 1 + n) % n;
        const anchorBefore = items[0].offsetLeft;
        track.prepend(figure);
        items.unshift(figure);
        // Reading offsetLeft after the mutation forces a layout recalc;
        // the difference equals the prepended item's layout width.
        track.scrollLeft += items[1].offsetLeft - anchorBefore;
    };

    // Maintain a fixed-size sliding window: BUFFER items on each side of the
    // active item. Grows and prunes in both directions so the DOM stays bounded.
    const maintainBuffer = () => {
        let activeIdx = findClosest();

        // Grow right
        while (items.length - 1 - activeIdx < BUFFER) appendNext();
        // Grow left
        while (activeIdx < BUFFER) { prependNext(); activeIdx++; }

        // Prune right excess (no scrollLeft compensation needed)
        while (items.length - 1 - activeIdx > 2 * BUFFER) items.pop().remove();

        // Prune left excess (compensate scrollLeft so view doesn't jump)
        if (activeIdx > 2 * BUFFER && items.length >= 2) {
            const stride = items[1].offsetLeft - items[0].offsetLeft;
            while (activeIdx > 2 * BUFFER) {
                items.shift().remove();
                track.scrollLeft -= stride;
                activeIdx--;
            }
        }
    };

    const easeOutCubic = (t) => 1 - Math.pow(1 - t, 3);

    const slideBy = (delta, done) => {
        const start = track.scrollLeft;
        const t0 = performance.now();
        isAnimating = true;
        const tick = (now) => {
            if (!autoplayActive) { animRaf = 0; isAnimating = false; return; }
            const elapsed = now - t0;
            const p = Math.min(1, elapsed / AUTOPLAY_ANIM_MS);
            track.scrollLeft = start + delta * easeOutCubic(p);
            if (p < 1) { animRaf = requestAnimationFrame(tick); }
            else { animRaf = 0; isAnimating = false; done && done(); }
        };
        animRaf = requestAnimationFrame(tick);
    };

    let autoplayActive = false;
    let isPaused = false;
    let dwellTimer = 0;
    let animRaf = 0;
    let isAnimating = false;

    const stepNext = () => {
        if (!autoplayActive || items.length < 2) return;
        const stride = items[1].offsetLeft - items[0].offsetLeft;
        slideBy(stride, () => {
            maintainBuffer();
            if (autoplayActive) dwellTimer = setTimeout(stepNext, AUTOPLAY_DWELL_MS);
        });
    };

    const stopAutoplay = () => {
        autoplayActive = false;
        if (dwellTimer) { clearTimeout(dwellTimer); dwellTimer = 0; }
        if (animRaf) { cancelAnimationFrame(animRaf); animRaf = 0; }
        snapToNearest();
        track.style.scrollSnapType = '';
    };

    const startAutoplay = (initialDelay = AUTOPLAY_DWELL_MS) => {
        if (isPaused || items.length <= 1 || autoplayActive) return;
        track.style.scrollSnapType = 'none';
        autoplayActive = true;
        dwellTimer = setTimeout(stepNext, initialDelay);
    };

    // Pointer drag → turn carousel left/right.
    // A short tap (< 10 px movement, < 200 ms) toggles autoplay; a real drag scrolls the track.
    // The duration cap prevents a slow finger press from being read as a tap on touch devices.
    const TAP_MAX_PX = 10;
    const TAP_MAX_MS = 200;
    let dragStartX = 0;
    let dragStartScroll = 0;
    let dragStartTime = 0;
    let isDragging = false;
    let hasDragged = false;

    track.addEventListener('pointerdown', (e) => {
        isDragging = true;
        hasDragged = false;
        dragStartX = e.clientX;
        dragStartScroll = track.scrollLeft;
        dragStartTime = performance.now();
        track.setPointerCapture(e.pointerId);
        track.style.scrollSnapType = 'none';
        track.style.cursor = 'grabbing';
    });

    track.addEventListener('pointermove', (e) => {
        if (!isDragging) return;
        const dx = dragStartX - e.clientX;
        if (Math.abs(dx) > TAP_MAX_PX) hasDragged = true;
        if (hasDragged) {
            if (autoplayActive) { isPaused = true; stopAutoplay(); }
            track.scrollLeft = dragStartScroll + dx;
        }
    });

    track.addEventListener('pointerup', () => {
        if (!isDragging) return;
        isDragging = false;
        track.style.cursor = '';
        const wasTap = !hasDragged && (performance.now() - dragStartTime) < TAP_MAX_MS;
        if (!wasTap) {
            maintainBuffer();
            snapToNearest();
            track.style.scrollSnapType = '';
            isPaused = false;
            startAutoplay(AUTOPLAY_DWELL_MS);
        } else {
            // Tap: toggle autoplay
            track.style.scrollSnapType = '';
            if (autoplayActive) {
                isPaused = true;
                stopAutoplay();
            } else {
                isPaused = false;
                startAutoplay(400);
            }
        }
    });

    track.addEventListener('pointercancel', () => {
        isDragging = false;
        track.style.cursor = '';
        track.style.scrollSnapType = '';
        maintainBuffer();
        snapToNearest();
        isPaused = false;
        startAutoplay(AUTOPLAY_DWELL_MS);
    });

    let scrollRaf = 0;
    track.addEventListener('scroll', () => {
        if (scrollRaf) return;
        scrollRaf = requestAnimationFrame(() => {
            scrollRaf = 0;
            if (!isDragging && !isAnimating) maintainBuffer();
            updateActive();
        });
    });

    requestAnimationFrame(() => {
        const seedIdx = Math.max(1, Math.floor(n / 2));
        const seed = items[seedIdx];
        // Rough scroll to bring the seed item into the viewport.
        track.scrollLeft = seed.offsetLeft + seed.offsetWidth / 2 - track.clientWidth / 2;
        maintainBuffer();
        updateActive();
        // Second RAF: margins have reflowed after updateActive; use getBoundingClientRect for exact centering.
        requestAnimationFrame(() => {
            snapToNearest();
            startAutoplay();
        });
    });
}

document.addEventListener('DOMContentLoaded', async () => {
    pickHeroImage();
    await renderReferences();
    setLang(detectLang());

    const switcher = document.querySelector('.lang-switcher');

    switcher.addEventListener('click', (e) => {
        const btn = e.target.closest('button[data-lang]');
        if (!btn) return;
        const isOpen = switcher.classList.contains('is-open');
        if (!isOpen) {
            switcher.classList.add('is-open');
        } else if (btn.getAttribute('aria-pressed') === 'true') {
            switcher.classList.remove('is-open');
        } else {
            setLang(btn.dataset.lang);
            switcher.classList.remove('is-open');
        }
    });

    document.addEventListener('click', (e) => {
        if (!switcher.contains(e.target)) {
            switcher.classList.remove('is-open');
        }
    });

    const hero = document.querySelector('#hero');
    if (hero) {
        new IntersectionObserver(
            ([entry]) => switcher.classList.toggle('is-past-hero', !entry.isIntersecting),
            { threshold: 0 }
        ).observe(hero);
    }

    const backToTop = document.getElementById('back-to-top');
    if (backToTop) {
        const contact = document.getElementById('contact');
        if (contact) {
            new IntersectionObserver(
                ([entry]) => backToTop.classList.toggle('is-visible', entry.isIntersecting),
                { threshold: 0.1 }
            ).observe(contact);
        }

        backToTop.addEventListener('click', () => {
            const start = window.scrollY;
            const duration = 1200;
            const t0 = performance.now();
            const easeInOutExpo = (t) =>
                t === 0 ? 0 : t === 1 ? 1
                    : t < 0.5 ? Math.pow(2, 20 * t - 10) / 2
                    : (2 - Math.pow(2, -20 * t + 10)) / 2;
            const tick = (now) => {
                const p = Math.min(1, (now - t0) / duration);
                window.scrollTo(0, start * (1 - easeInOutExpo(p)));
                if (p < 1) requestAnimationFrame(tick);
            };
            requestAnimationFrame(tick);
        });
    }

    const copyrightEl = document.querySelector('.contact-copyright');
    if (copyrightEl) {
        copyrightEl.textContent = `Copyright © 2014–${new Date().getFullYear()} Nategra`;
    }

    document.querySelectorAll('[data-modal-open]').forEach((trigger) => {
        const modal = document.getElementById(trigger.dataset.modalOpen);
        if (!modal) return;
        trigger.addEventListener('click', () => modal.showModal());
    });

    document.querySelectorAll('dialog').forEach((modal) => {
        modal.querySelector('[data-modal-close]')
            ?.addEventListener('click', () => modal.close());
        modal.addEventListener('click', (e) => {
            if (e.target === modal) modal.close();
        });
    });
});
